# -*- coding: utf-8 -*-
"""Diabetes.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1_Zsg43J3f5AsKZ9UrekFSfFxh7n6iSol
"""

from google.colab import drive
drive.mount('/content/drive')
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
from sklearn.datasets import load_diabetes
from sklearn.linear_model import LinearRegression
from sklearn.metrics import mean_squared_error
from sklearn.model_selection import train_test_split

data = pd.read_csv("drive/My Drive/datasets/diabetes.csv")

diabetes = load_diabetes()

X = diabetes.data
Y = diabetes.target

X_train, X_test, Y_train, Y_test = train_test_split(X,Y, train_size = 0.9)

model = LinearRegression()

model.fit(X_train,Y_train)

Y_pred = model.predict(X_test)

print("actual values",Y_test)
print("predict values",Y_pred)

rmse = np.sqrt(mean_squared_error(Y_test, Y_pred))
print(f"Root Mean Squared Error (RMSE): {rmse:.2f}")


# Plot actual vs. predicted values
plt.plot( Y_test, 'b', label='Real Data')
plt.plot( Y_pred, 'r', label='Predicted Data')

